site_name: embARC Documentation Site for ARC Classic
repo_url: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain
repo_name: GNU ARC Toolchain
copyright: Copyright &copy; 2016 - 2025 Synopsys
theme:
  name: material
  highlightjs: true
  locale: en
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: deep purple
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    # Use this option to integrate the local table of content
    # in the side bar:
    # - toc.integrate
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - content.code.copy
plugins:
  - table-reader
  - search
  - autorefs
extra:
  version:
    provider: mike
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
  - footnotes
  - tables
  - attr_list
  - def_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home:
    - index.md
    - home/processors.md
    - home/faq.md
  - Toolchain:
    - toolchain/index.md
    - Target Options:
      - toolchain/options/arcv3.md
      - toolchain/options/arcv2.md
      - toolchain/options/arcompact.md
    - Advanced:
      - toolchain/advanced/optimizations.md
      - toolchain/advanced/custom-instructions.md
      - toolchain/advanced/apex-header.md
      - toolchain/advanced/intrinsics.md
      - toolchain/advanced/sanitizers.md
      - toolchain/advanced/jli.md
      - toolchain/advanced/secure-shield.md
      - toolchain/advanced/small-data.md
      - toolchain/advanced/64-bit-operations.md
    - Libraries:
      - Audio:
        - audio/index.md
        - General:
          - audio/overview.md
          - audio/getting-started.md
        - Codecs:
          - audio/codecs.md
          - audio/codec-bt-cvsd.md
          - audio/codec-gsm-fr.md
          - audio/codec-g711.md
          - audio/codec-g722.md
          - audio/codec-g726.md
          - audio/codec-ldac.md
      - Machine Learning:
        - ml/index.md
        - embARC MLI: ml/mli.md
        - Caffe Framework for EV6x: ml/caffe-framework.md
        - Caffe Models for EV6x: ml/caffe-models.md
        - OpenCV for EV6x: ml/opencv.md
        - GSL for EV6x: ml/gsl.md
      - IoT:
        - iot/index.md
        - embARC OSP: iot/embarc-osp.md
        - embARC BSP: iot/embarc-bsp.md
    - Testing:
      - toolchain/testing/dejagnu.md
      - toolchain/testing/glibc.md
  - Simulators:
    - simulators/qemu.md
    - simulators/nsim.md
  - Baremetal:
    - baremetal/index.md
    - Simulators:
      - baremetal/simulators/nsim.md
      - baremetal/simulators/qemu.md
    - Development platforms:
      - baremetal/hardware/hsdk.md
      - baremetal/hardware/emsdp.md
      - baremetal/hardware/iotdk.md
      - baremetal/hardware/emsk.md
      - baremetal/hardware/axs-openocd.md
      - baremetal/hardware/axs-ashling.md
    - General Topics:
      - baremetal/general/memory.md
      - baremetal/general/specs.md
      - baremetal/general/interrupts.md
      - baremetal/general/heap-and-stack.md
      - baremetal/general/tcf.md
  - Linux:
    - linux/index.md
    - Building Linux:
      - linux/building/buildroot.md
      - linux/building/separate.md
      - linux/building/configure.md
      - linux/building/toolchain.md
    - Running Linux on simulators:
      - linux/simulators/nsim.md
      - linux/simulators/metaware.md
      - linux/simulators/vdk.md
      - linux/simulators/qemu.md
    - Running Linux on HS Development Kit:
      - Building and running Linux: linux/hsdk/build.md
      - Building U-Boot: linux/hsdk/uboot-build.md
      - U-Boot command reference: linux/hsdk/uboot-commands.md
    - Running Linux on AXS SDP:
      - Building and running Linux: linux/axs/build.md
      - Flashing U-Boot: linux/axs/uboot.md
    - Linux eBPF subsystem:
      - linux/ebpf/cross.md
      - linux/ebpf/build.md
      - linux/ebpf/clang.md
  - Boards:
    - platforms/index.md
    - Using Boards:
      - platforms/get-openocd.md
      - platforms/use-openocd.md
      - platforms/mdb.md
      - platforms/winusb.md
      - platforms/digilent.md
      - platforms/reset.md
      - platforms/bit-file-fpga.md
    - Boards Documentation:
      - platforms/board-hsdk-4xd.md
      - platforms/board-hsdk.md
      - platforms/board-emsdp.md
      - platforms/board-iot.md
      - platforms/board-emsk.md
      - platforms/board-axs103.md
      - platforms/board-axs101.md
  - Eclipse IDE:
    - eclipse/index.md
    - Installation:
      - Installing on Windows: eclipse/installation/windows.md
      - Installing on Linux: eclipse/installation/linux.md
      - Manual Installation: eclipse/installation/manual.md
      - eclipse/installation/preferences.md
    - Getting Started:
      - EM Software Development Platform: eclipse/getting-started/emsdp.md
      - HS Development Kit: eclipse/getting-started/hsdk.md
      - EM Starter Kit: eclipse/getting-started/emsk.md
      - nSIM: eclipse/getting-started/nsim.md
    - Other:
      - eclipse/other/build-settings.md
      - eclipse/other/custom-gdb-server.md
      - eclipse/other/running-gdb-server.md
      - eclipse/other/building.md
