site_name: embARC Documentation Site for ARC Classic and ARC-V
repo_url: https://github.com/foss-for-mips-arc-processors/toolchain
repo_name: GNU ARC Toolchain
copyright: Copyright &copy; 2016 - 2026 MIPS Holding, Inc
theme:
  name: material
  highlightjs: true
  locale: en
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: deep purple
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    # Use this option to integrate the local table of content
    # in the side bar:
    # - toc.integrate
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - content.code.copy
plugins:
  - table-reader
  - search
  - autorefs
extra:
  version:
    provider: mike
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
  - footnotes
  - tables
  - attr_list
  - def_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home:
    - index.md
    - home/release.md
    - home/processors.md
  - Toolchain:
    - toolchain/index.md
    - toolchain/building-toolchains.md
    - ARC-V:
      - toolchain/arc-v/getting-started-picolibc.md
      - toolchain/arc-v/getting-started-newlib.md
      - toolchain/arc-v/running-on-nsim.md
      - toolchain/arc-v/running-on-qemu.md
      - toolchain/arc-v/multilib.md
      - toolchain/arc-v/testing.md
    - ARC Classic:
      - toolchain/arc-classic/getting-started-nsim.md
      - toolchain/arc-classic/getting-started-qemu.md
      - toolchain/arc-classic/getting-started-picolibc.md
      - toolchain/arc-classic/arcv3.md
      - toolchain/arc-classic/arcv2.md
      - toolchain/arc-classic/arcompact.md
      - toolchain/arc-classic/memory.md
      - toolchain/arc-classic/faq.md
      - Advanced Topics:
        - toolchain/arc-classic/advanced/optimizations.md
        - toolchain/arc-classic/advanced/custom-instructions.md
        - toolchain/arc-classic/advanced/apex-header.md
        - toolchain/arc-classic/advanced/intrinsics.md
        - toolchain/arc-classic/advanced/sanitizers.md
        - toolchain/arc-classic/advanced/jli.md
        - toolchain/arc-classic/advanced/secure-shield.md
        - toolchain/arc-classic/advanced/small-data.md
        - toolchain/arc-classic/advanced/64-bit-operations.md
        - toolchain/arc-classic/advanced/interrupts.md
        - toolchain/arc-classic/advanced/tcf.md
      - Libraries:
        - Audio:
          - toolchain/arc-classic/libs/audio/index.md
          - General:
            - toolchain/arc-classic/libs/audio/overview.md
            - toolchain/arc-classic/libs/audio/getting-started.md
          - Codecs:
            - toolchain/arc-classic/libs/audio/codecs.md
            - toolchain/arc-classic/libs/audio/codec-bt-cvsd.md
            - toolchain/arc-classic/libs/audio/codec-gsm-fr.md
            - toolchain/arc-classic/libs/audio/codec-g711.md
            - toolchain/arc-classic/libs/audio/codec-g722.md
            - toolchain/arc-classic/libs/audio/codec-g726.md
            - toolchain/arc-classic/libs/audio/codec-ldac.md
        - Machine Learning:
          - toolchain/arc-classic/libs/ml/index.md
          - embARC MLI: toolchain/arc-classic/libs/ml/mli.md
          - Caffe Framework for EV6x: toolchain/arc-classic/libs/ml/caffe-framework.md
          - Caffe Models for EV6x: toolchain/arc-classic/libs/ml/caffe-models.md
          - OpenCV for EV6x: toolchain/arc-classic/libs/ml/opencv.md
          - GSL for EV6x: toolchain/arc-classic/libs/ml/gsl.md
        - IoT:
          - toolchain/arc-classic/libs/iot/index.md
          - embARC OSP: toolchain/arc-classic/libs/iot/embarc-osp.md
          - embARC BSP: toolchain/arc-classic/libs/iot/embarc-bsp.md
  - Linux:
    - linux/index.md
    - Building Linux:
      - linux/building/buildroot.md
      - linux/building/configure.md
      - linux/building/toolchain.md
    - Running Linux on simulators:
      - linux/simulators/nsim.md
      - linux/simulators/metaware.md
      - linux/simulators/qemu.md
    - Running Linux on HS Development Kit:
      - Building and running Linux: linux/hsdk/build.md
      - Building U-Boot: linux/hsdk/uboot-build.md
      - U-Boot command reference: linux/hsdk/uboot-commands.md
    - Linux eBPF subsystem:
      - linux/ebpf/cross.md
      - linux/ebpf/build.md
      - linux/ebpf/clang.md
  - Development Platforms:
    - platforms/index.md
    - Boards:
      - platforms/board-hsdk.md
      - platforms/board-emsdp.md
    - OpenOCD:
      - platforms/get-openocd.md
      - platforms/use-openocd.md
    - Other guides:
      - platforms/mdb.md
      - platforms/winusb.md
      - platforms/digilent.md
      - platforms/reset.md
  - Eclipse IDE:
    - eclipse/index.md
    - Installation:
      - Installing on Windows: eclipse/installation/windows.md
      - Installing on Linux: eclipse/installation/linux.md
      - Manual Installation: eclipse/installation/manual.md
      - eclipse/installation/preferences.md
    - Getting Started:
      - EM Software Development Platform: eclipse/getting-started/emsdp.md
      - HS Development Kit: eclipse/getting-started/hsdk.md
      - nSIM: eclipse/getting-started/nsim.md
    - Other:
      - eclipse/other/build-settings.md
      - eclipse/other/custom-gdb-server.md
      - eclipse/other/running-gdb-server.md
      - eclipse/other/building.md
