site_name: GNU Toolchain for ARC User Manual
repo_url: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain
repo_name: GNU ARC Toolchain
copyright: Copyright &copy; 2016 - 2023 Synopsys
theme:
  name: material
  highlightjs: true
  locale: en
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: deep purple
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - toc.integrate
    - navigation.sections
    - navigation.indexes
    - navigation.top
plugins:
  - table-reader
  - search
  - autorefs
markdown_extensions:
  - admonition
  - footnotes
  - tables
  - attr_list
  - def_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home:
    - index.md
    - general/processors.md
    - general/toolchains.md
    - general/target-options.md
    - general/compatibility.md
  - Simulators:
    - simulators/qemu.md
    - simulators/nsim.md
  - Baremetal:
    - Simulators:
      - baremetal/simulators/nsim.md
      - baremetal/simulators/qemu.md
    - Hardware:
      - baremetal/hardware/memory.md
      - baremetal/hardware/debugging.md
      - baremetal/hardware/axs-openocd.md
      - baremetal/hardware/axs-ashling.md
    - General Topics:
      - baremetal/general/heap-and-stack.md
      - baremetal/general/tcf.md
      - baremetal/general/specs.md
  - Linux: https://github.com/foss-for-synopsys-dwc-arc-processors/linux/wiki
  - Development platforms:
    - platforms/index.md
    - Using Boards:
      - platforms/get-openocd.md
      - platforms/use-openocd.md
      - platforms/winusb.md
      - platforms/digilent.md
      - platforms/reset.md
    - Boards Documentation:
      - ARC HS Development Kit 4xD: https://github.com/foss-for-synopsys-dwc-arc-processors/ARC-Development-Systems-Forum/wiki/ARC-Development-Systems-Forum-Wiki-Home#arc-hs4xhs4xd-development-kit-1
      - ARC HS Development Kit: https://github.com/foss-for-synopsys-dwc-arc-processors/ARC-Development-Systems-Forum/wiki/ARC-Development-Systems-Forum-Wiki-Home#arc-hs-development-kit-1
      - ARC EM SDP: https://github.com/foss-for-synopsys-dwc-arc-processors/ARC-Development-Systems-Forum/wiki/ARC-Development-Systems-Forum-Wiki-Home#arc-em-software-development-platform-sdp-1
      - ARC IoT Development Kit: https://github.com/foss-for-synopsys-dwc-arc-processors/ARC-Development-Systems-Forum/wiki/ARC-Development-Systems-Forum-Wiki-Home#arc-iot-development-kit-1
      - ARC EM Starter Kit: https://github.com/foss-for-synopsys-dwc-arc-processors/ARC-Development-Systems-Forum/wiki/ARC-Development-Systems-Forum-Wiki-Home#arc-em-starter-kit-1
      - ARC AXS 103 SDP: https://github.com/foss-for-synopsys-dwc-arc-processors/ARC-Development-Systems-Forum/wiki/ARC-Development-Systems-Forum-Wiki-Home#arc-axs103-software-development-platform-1
      - ARC AXS 101 SDP: https://github.com/foss-for-synopsys-dwc-arc-processors/ARC-Development-Systems-Forum/wiki/ARC-Development-Systems-Forum-Wiki-Home#arc-axs101-software-development-platform-1
  - Eclipse IDE:
    - eclipse/index.md
    - Installation:
      - Installing on Windows: eclipse/installation/windows.md
      - Installing on Linux: eclipse/installation/linux.md
      - Manual Installation: eclipse/installation/manual.md
      - eclipse/installation/preferences.md
    - Getting Started:
      - EM Starter Kit: eclipse/getting-started/emsk.md
      - HS Development Kit: eclipse/getting-started/hsdk.md
      - nSIM: eclipse/getting-started/nsim.md
    - Other:
      - eclipse/other/building.md
  - Advanced topics:
    - advanced/optimizations.md
    - advanced/custom-instructions.md
    - advanced/apex-header.md
    - advanced/intrinsics.md
    - advanced/sanitizers.md
    - advanced/jli.md
    - advanced/secure-shield.md
    - advanced/small-data.md
    - advanced/64-bit-operations.md
    - advanced/bit-file-fpga.md
  - Testing:
    - testing/newlib.md
    - testing/glibc.md
    - testing/gcc.md
    - testing/qemu.md
  - FAQ: faq.md
